# Numpy:
It provides a high-performance multidimensional array object, and tools for working with these arrays. 


Array: A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

In [5]:
import numpy as np


a=np.array([2,3,4])
print(a)
print(type(a))
print(a.shape)
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)

[2 3 4]
<class 'numpy.ndarray'>
(3,)
(2, 3)



# Numpy also provides many functions to create arrays:

In [17]:
zeroArray=np.zeros((3,2))
print(zeroArray)
print("\n")

onesArray=np.ones((2,2))
print(onesArray)
print("\n")


fillArray=np.full((3,3),4)
print(fillArray)
print("\n")


identityArray=np.eye(9)
print(identityArray)
print("\n")

randomArray=np.random.random((2,3))
print(randomArray)
print("\n")


[[0. 0.]
 [0. 0.]
 [0. 0.]]


[[1. 1.]
 [1. 1.]]


[[4 4 4]
 [4 4 4]
 [4 4 4]]


[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


[[0.52649906 0.63103658 0.66693659]
 [0.32215307 0.91529013 0.17590468]]




In [18]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77
