# NumPy (Numeric Python) is a Python package used for building multi dimensional arrays and performing
# various operations

# In this program we will walk through various concepts and see available functions in the NumPy package.

# For installing: pip3 install numpy


In [44]:
import numpy as np

# we have a function arange() which makes an array of the specified dimension. Example:
 # [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [45]:
myArray=np.arange(20)
print(myArray)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


# an array from 10 to 20

In [46]:
myArray=np.arange(10,20)
print(myArray)

[10 11 12 13 14 15 16 17 18 19]


# an array from 10 to 20 with 2 steps

In [47]:
myArray=np.arange(10,20,2)
print(myArray)

[10 12 14 16 18]


# reshape() helps to reshape our NumPy array
# [[ 0  1  2  3  4]
#  [ 5  6  7  8  9]
#  [10 11 12 13 14]
#  [15 16 17 18 19]]

In [48]:
myArray=np.arange(20)

# syntax: reshape(number_of_rows, number_of_columns)
myArray=myArray.reshape(4,5)
print(myArray)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [49]:
myArray=myArray.reshape(10,2)
print(myArray)

myArray=myArray.reshape(2,10)
print(myArray)


[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [50]:
# shape returns the shape of the array. The length of shape tuple is called as rank (or dimension)
print(myArray.shape)     # (2,10)


(2, 10)


In [51]:
# ndim returns the dimension (rank) of the array
print(myArray.ndim)         # 2

2


In [52]:
# size returns the total number of elements in the array
print(myArray.size)         # 20

20


In [53]:
# to check the data we have dtype.
print(myArray.dtype)        # int64
print(type(myArray))  

int32
<class 'numpy.ndarray'>


In [54]:

# zeros creates an array will all zeros
myArray=np.zeros((4,5))
print(myArray)

# [[ 0.  0.  0.  0.]
#  [ 0.  0.  0.  0.]
#  [ 0.  0.  0.  0.]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [55]:
# ones creates an array with all ones
myArray=np.ones((1,1))
print(myArray)
# [[ 1.  1.  1.  1.]
#  [ 1.  1.  1.  1.]
#  [ 1.  1.  1.  1.]]


[[1.]]




# numpy random module helps to initialize array with random values


# [[ 0.54808903  0.08750717  0.23886267  0.93589283]
#  [ 0.90750146  0.31197039  0.54013725  0.91092763]
#  [ 0.38827674  0.04647878  0.15997665  0.94909537]]

In [56]:
myArray=np.random.rand(3,4)
print(myArray)

[[0.98838901 0.8946078  0.23093264 0.78017507]
 [0.5694251  0.95510079 0.34242639 0.99592135]
 [0.78297154 0.679229   0.86536279 0.99225118]]
