# This example shows various array manipulation operations

In [1]:
import numpy as np

In [2]:
myArray=np.arange(0,50,2)
print(myArray)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]


# numpy.reshape(array_to_reshape, tuple_of_new_shape) gives new shape (dimension) to our array

In [3]:
myArray=myArray.reshape(5,5)
print(myArray)

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]]


# numpy.ndarray.flat() returns an 1-D iterator

In [24]:
#Confused about this

print(myArray.flat[24])


48


# numpy.ndarray.flatten() restores the reshaped array into a 1-D array

In [15]:
print(myArray.flatten())

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]


# numpy.tranpose() this helps to find the tranpose of the given array

In [16]:
print(myArray.transpose())

[[ 0 10 20 30 40]
 [ 2 12 22 32 42]
 [ 4 14 24 34 44]
 [ 6 16 26 36 46]
 [ 8 18 28 38 48]]


# numpy.swapaxes(array, axis1, axis2) interchanges the two axes of an array

In [33]:
originalArray=np.arange(25).reshape(5,5)
print(OriginalArray)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [34]:
print(np.swapaxes(originalArray, 0, 1))

[[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]


# numpy.rollaxis(arr, axis, start) rolls the specified axis backwards, until it lies in a specified position

In [44]:
print(np.rollaxis(originalArray,1))
print("\n",np.rollaxis(originalArray,0))


[[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]

 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [47]:
# numpy.resize(arr, shape) returns a new array with the specified size. If the new size is greater than
# the original, the repeated copies of entries in the original are contained

myArray = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(myArray)

# [[1 2 3]
#  [4 5 6]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [54]:
print((myArray, (5, 2)))

# [[1 2]
#  [3 4]
#  [5 6]]


(array([[1, 2, 3],
       [4, 5, 6]]), (5, 2))


In [51]:

# numpy.append(array, values, axis)
myArray = np.array([[1,2,3],[4,5,6]])
print(myArray)

# [[1 2 3]
#  [4 5 6]]

[[1 2 3]
 [4 5 6]]


In [52]:

print(np.append(myArray, [7, 8, 9]))

# [1 2 3 4 5 6 7 8 9]

[1 2 3 4 5 6 7 8 9]


In [53]:

firstArray = np.arange(12).reshape(3, 4)
print(firstArray)

secondArray = np.arange(4)
print(secondArray)

# adding above two arrays (NOTE: array shapes should be same)
print(np.add(firstArray, secondArray))

# subtracting above two arrays
print(np.subtract(firstArray, secondArray))

# multiplying above two arrays
print(np.multiply(firstArray, secondArray))

# dividing the above two arrays
print(np.divide(firstArray, secondArray))

# numpy.power(): returns array element raised to the specified value result
array = np.array([1, 2, 3])
print(np.power(array, 2))       # [1 4 9]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]]
[[0 0 0 0]
 [4 4 4 4]
 [8 8 8 8]]
[[ 0  1  4  9]
 [ 0  5 12 21]
 [ 0  9 20 33]]
[[       nan 1.         1.         1.        ]
 [       inf 5.         3.         2.33333333]
 [       inf 9.         5.         3.66666667]]
[1 4 9]


<ipython-input-53-fbc7930beb9d>:17: RuntimeWarning: divide by zero encountered in true_divide
  print(np.divide(firstArray, secondArray))
<ipython-input-53-fbc7930beb9d>:17: RuntimeWarning: invalid value encountered in true_divide
  print(np.divide(firstArray, secondArray))
